version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "marcelo" # Replace with your GitHub username
    assignees:
      - "marcelo" # Replace with your GitHub username
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    groups:
      # Group React-related updates
      react:
        patterns:
          - "react*"
          - "@types/react*"
      # Group Next.js related updates
      nextjs:
        patterns:
          - "next*"
          - "@next/*"
      # Group Radix UI updates
      radix:
        patterns:
          - "@radix-ui/*"
      # Group development dependencies
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "eslint*"
          - "typescript"
          - "tailwindcss"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "marcelo" # Replace with your GitHub username
    assignees:
      - "marcelo" # Replace with your GitHub username
    commit-message:
      prefix: "ci"
      include: "scope"